"""Initial migration

Revision ID: 8953fd549938
Revises: 
Create Date: 2024-07-10 23:30:36.048926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8953fd549938'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plot_filename', sa.String(length=100), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('analysis_entry', schema=None) as batch_op:
        batch_op.drop_column('plot_filename')

    # ### end Alembic commands ###
